- job:
    name: python-zaqarclient-functional
    parent: devstack-tox-functional
    required-projects:
      - opendev.org/openstack/horizon
      - opendev.org/openstack/python-zaqarclient
      - opendev.org/openstack/zaqar
      - opendev.org/openstack/zaqar-tempest-plugin
    vars:
      devstack_plugins:
        zaqar: https://opendev.org/openstack/zaqar
      devstack_services:
        # it does not seem to work with tls-proxy at the time
        # of the legacy -> Zuul v3 porting
        tls-proxy: false
        # probably other services can be disabled;
        # the old legacy job only uses mysql, keystone, zaqar and tempest
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        c-bak: false
      # FIXME: only a few functional tests work at the end of Victoria cycle
      # when they have been enabled again by a native Zuul v3 job.
      # The failing job can be checked by removing this filter.
      tox_extra_args: -vv -- tests.functional.queues.v2.test_health
      tox_environment:
        ZAQAR_ENDPOINT: "http://localhost/messaging"

- project:
    templates:
      - check-requirements
      - openstack-python3-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - python-zaqarclient-functional
    gate:
      jobs:
        - python-zaqarclient-functional
